exp: TextClassification
mode: 
    - train
    
models: 
    hf_text_classification_model:
        - distilbert/distilgpt2
        # - distilbert/distilbert-base-cased
          
trainfpath: /home/eheng/NLPScholarFork/final_project/Algebra_train_final
validfpath: /home/eheng/NLPScholarFork/final_project/Algebra_val_final
modelfpath: /home/eheng/NLPScholarFork/final_project/Algebra_distilgpt2
loadPretrained: False
numLabels: 2
id2label:
    1: Positive
    0: Negative

# exp: TextClassification
# mode: 
#     - evaluate
    
# models: 
#     hf_text_classification_model:
#         - /home/eheng/NLPScholarFork/final_project/Algebra_distilbert

# datafpath: /home/eheng/NLPScholarFork/final_project/test_tsvs_by_model/Algebra_test_final.tsv
# predfpath: /home/eheng/NLPScholarFork/final_project/Algebra_distilbert_predictions.tsv

# id2label:
#     1: Positive
#     0: Negative